# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HexaText.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainText = QtWidgets.QTextBrowser(self.centralwidget)
        self.mainText.setGeometry(QtCore.QRect(10, 30, 481, 691))
        self.mainText.setObjectName("mainText")
        self.replaceText = QtWidgets.QTextBrowser(self.centralwidget)
        self.replaceText.setGeometry(QtCore.QRect(520, 29, 471, 691))
        self.replaceText.setObjectName("replaceText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(14, 7, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(522, 7, 91, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuEncoding = QtWidgets.QMenu(self.menubar)
        self.menuEncoding.setObjectName("menuEncoding")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.btnOpen = QtWidgets.QAction(MainWindow)
        self.btnOpen.setObjectName("btnOpen")
        self.btnSave = QtWidgets.QAction(MainWindow)
        self.btnSave.setObjectName("btnSave")
        self.actionHexa = QtWidgets.QAction(MainWindow)
        self.actionHexa.setObjectName("actionHexa")
        self.btnUTF = QtWidgets.QAction(MainWindow)
        self.btnUTF.setCheckable(True)
        self.btnUTF.setChecked(True)
        self.btnUTF.setObjectName("btnUTF")
        self.btnANSI = QtWidgets.QAction(MainWindow)
        self.btnANSI.setCheckable(True)
        self.btnANSI.setObjectName("btnANSI")
        self.menuFile.addAction(self.btnOpen)
        self.menuFile.addAction(self.btnSave)
        self.menuOption.addAction(self.actionHexa)
        self.menuEncoding.addAction(self.btnUTF)
        self.menuEncoding.addAction(self.btnANSI)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuEncoding.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Main Text"))
        self.label_2.setText(_translate("MainWindow", "Replace Text"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuEncoding.setTitle(_translate("MainWindow", "Encoding"))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.actionHexa.setText(_translate("MainWindow", "Hexa"))
        self.btnUTF.setText(_translate("MainWindow", "UTF-8"))
        self.btnANSI.setText(_translate("MainWindow", "ANSI"))
        self.btnOpen.triggered.connect(self.btn_Open)
        self.btnSave.triggered.connect(self.btn_Save)
        self.actionHexa.triggered.connect(self.convert)
        self.btnUTF.triggered.connect(self.ckUTF)
        self.btnANSI.triggered.connect(self.ckANSI)
        
    def ckUTF(self) :
        if self.btnUTF.isChecked() :
            self.btnANSI.setChecked(False)
        else :
            self.btnANSI.setChecked(True)

    def ckANSI(self) :
        if self.btnANSI.isChecked() :
            self.btnUTF.setChecked(False)
        else : 
            self.btnUTF.setChecked(True)

    def btn_Open(self) :
        a = QtWidgets.QFileDialog.getOpenFileName()
        if self.btnUTF.isChecked() :
            enco = 'UTF-8'
        elif self.btnANSI.isChecked() :
            enco = 'ANSI'

        f = open(a[0], 'r', encoding = enco)

        # for i in f :
        #     self.mainText.setText(i)
        self.mainText.setText(f.read())

    def btn_Save(self) :
        a = QtWidgets.QFileDialog.getOpenFileName()
        s = self.mainText.toPlainText()
        if self.btnUTF.isChecked() :
            enco = 'UTF-8'
        elif self.btnANSI.isChecked() :
            enco = 'ANSI'

        f = open(a[0], 'w', encoding = enco)
        f.write(s) 

    def convert(self) :
        s = self.mainText.toPlainText()
        c = s.encode('ANSI')
        cInt = int.from_bytes(c, 'big')


    def convert(self) :
        

        f = open(s, encoding = es)
        s1 = f.read()
        s2 = ""
        b = bytearray(s1, es)
        for i in range(len(b)) :        # 위의 for 문과 결과는 동일하지만 index 값으로 주는 것이 분별을 명확히 할 수 있다
            if (i % 16 == 0) :
                s2.append(f"{'%08X'%i} : ", end = ' ')      # 포맷문자열 안에서의 콜론(:)의 의미 : 인덱스 앞 ~ 뒤
            s2.append(f"{'%02X'%b[i]}", end = ' ')      
            if((i + 1) % 8 == 0) :
                if((i + 1) % 16 == 0) :
                    s2.append("")
                else : s2.append("| ", end = ' ')
        self.tbTest.setText(s2)





        # blank = ""
        # b = s.encode('ANSI')
        # b2 = int.from_bytes(b, 'big')
        # # b3 = f"{'%2s'%blank}{'%02x'%b2}"
        # n = 0
        # for i in b2 :
            
        #     # b2 = int.from_bytes(i[n], 'big')
        #     b3 = f"{'%2s'%blank}{'%02x'%b2[i]}"
        #     self.replaceText.setText(b3)
        
        
        
        # b = s.encode('ANSI')
        # b2 = int.from_bytes(b, 'big')



        # for i in b2 :
        #     sSplit = s.split('\n')

        #     x = f"{'%2s'%''}{'%02x'%i}"
        #     f = f"{'%02x'%i}"
        #     self.replaceText.setText(x, i)
        # x = f"{'%2s'%''}{'%02x'%b2}"


        self.replaceText.setText(x)
        
        # if self.btnUTF.setChecked() :
        #     x = s.encode('UTF-8')
        #     fx = f"{'%02x'%x}"
        #     self.replaceText.setText(fx)
        
        # elif self.btnANSI.setChecked() :
        #     x = s.encode('ANSI')
        #     fx = f"{'%02x'%x}"
        #     self.replaceText.setText(fx)






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
